### ISSUE TITLE
Output bastion security group

### ISSUE THREAD

**Issue by aarcro** [remind101/stacker_blueprints#109]
As a network admin
I want to expose the bastion security group as an output
So I can pass it into other stacks which add ingress rules allowing traffic from the bastions

**Comment by russellballestrini** [comment]
Just to clarify you want the bastion security group `id` as an output?

If so, I think this could be as easy as adding the following to line 90:

```
        t.add_output(
            Output("SecurityGroupId", Value=Ref(CLUSTER_SG_NAME))
        )
```
